
Insert into WALMART_CUSTOMERS (CUSTOMER_NAME,CUSTOMER_ID,EMAIL_ID,MOBILE_NUMBER,REGISTRATION_DATE,ACCOUNT_STATUS) values ('johnsena',1,'johnyet99@gmil.com','9298272',to_date('17-07-26','DD-MM-RR'),'ACTIVE');
Insert into WALMART_CUSTOMERS (CUSTOMER_NAME,CUSTOMER_ID,EMAIL_ID,MOBILE_NUMBER,REGISTRATION_DATE,ACCOUNT_STATUS) values ('johnsenani',2,'johnyet999@gmil.com','92988272',to_date('17-07-26','DD-MM-RR'),'ACTIVE');
Insert into WALMART_CUSTOMERS (CUSTOMER_NAME,CUSTOMER_ID,EMAIL_ID,MOBILE_NUMBER,REGISTRATION_DATE,ACCOUNT_STATUS) values ('Ravi Kumar',201,'ravi.kumar@test.com','9000000001',to_date('03-08-26','DD-MM-RR'),'ACTIVE');
Insert into WALMART_CUSTOMERS (CUSTOMER_NAME,CUSTOMER_ID,EMAIL_ID,MOBILE_NUMBER,REGISTRATION_DATE,ACCOUNT_STATUS) values ('Anita Sharma',202,'anita.sharma@test.com','9000000002',to_date('03-08-26','DD-MM-RR'),'SUSPENDED');

Insert into WALMART_PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STOCK_QUANTITY,REORDER_THRESHOLD) values (99,'shampoo','skin_care',70,13,2);
Insert into WALMART_PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STOCK_QUANTITY,REORDER_THRESHOLD) values (909,'shampoo','skin_care',70,4,2);
Insert into WALMART_PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STOCK_QUANTITY,REORDER_THRESHOLD) values (301,'Wireless Mouse','Electronics',499,22,5);
Insert into WALMART_PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STOCK_QUANTITY,REORDER_THRESHOLD) values (302,'Mechanical Keyboard','Electronics',2999,7,5);
Insert into WALMART_PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STOCK_QUANTITY,REORDER_THRESHOLD) values (303,'USB-C Cable','Accessories',199,50,10);


Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (104,201,to_date('03-08-26','DD-MM-RR'),'CANCELLED',0);
Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (601,201,to_date('15-01-26','DD-MM-RR'),'CANCELLED',0);
Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (602,201,to_date('03-08-26','DD-MM-RR'),'PENDING',0);
Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (101,1,to_date('17-07-26','DD-MM-RR'),'CANCELLED',198);
Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (102,2,to_date('17-07-26','DD-MM-RR'),'CONFIRMED',98);
Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (401,201,to_date('03-08-26','DD-MM-RR'),'CANCELLED',0);
Insert into WALMART_ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT) values (402,201,to_date('02-02-97','DD-MM-RR'),'CANCELLED',0);

7 rows selected. 


Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (701,601,301,2,499);
Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (702,602,303,3,199);
Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (11,101,99,3,70);
Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (119,101,909,3,70);
Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (501,401,301,3,499);
Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (502,401,303,5,199);
Insert into WALMART_ORDERITEMS (ORDERITEM_ID,ORDER_ID,PRODUCT_ID,ORDER_QUANTITY,PRICE_AT_ORDER) values (503,402,302,5,2999);

7 rows selected. 



