
  CREATE TABLE "GOPI"."WALMART_CUSTOMERS" 
   (	"CUSTOMER_NAME" VARCHAR2(30 CHAR), 
	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"MOBILE_NUMBER" VARCHAR2(13 BYTE), 
	"REGISTRATION_DATE" DATE, 
	"ACCOUNT_STATUS" VARCHAR2(20 CHAR), 
	 CONSTRAINT "WALMART_CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WALMART_CUSTOMERS__UN" UNIQUE ("EMAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WALMART_CUSTOMERS__UNV1" UNIQUE ("MOBILE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CHECK_STATUS" CHECK (ACCOUNT_STATUS in ('ACTIVE','INACTIVE','SUSPENDED')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;




  CREATE TABLE "GOPI"."WALMART_CUSTOMERS" 
   (	"CUSTOMER_NAME" VARCHAR2(30 CHAR), 
	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"MOBILE_NUMBER" VARCHAR2(13 BYTE), 
	"REGISTRATION_DATE" DATE, 
	"ACCOUNT_STATUS" VARCHAR2(20 CHAR), 
	 CONSTRAINT "WALMART_CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WALMART_CUSTOMERS__UN" UNIQUE ("EMAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WALMART_CUSTOMERS__UNV1" UNIQUE ("MOBILE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CHECK_STATUS" CHECK (ACCOUNT_STATUS in ('ACTIVE','INACTIVE','SUSPENDED')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



  CREATE TABLE "GOPI"."WALMART_ORDERITEMS" 
   (	"ORDERITEM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDER_QUANTITY" NUMBER(10,0), 
	"PRICE_AT_ORDER" NUMBER(10,2), 
	 CONSTRAINT "WALMART_ORDERITEMS_PK" PRIMARY KEY ("ORDERITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CHECK_ORDERITEMS" CHECK (order_quantity >0) ENABLE, 
	 CONSTRAINT "WALMART_ORDERITEMS_FK2" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "GOPI"."WALMART_ORDERS" ("ORDER_ID") ENABLE, 
	 CONSTRAINT "WALMART_ORDERITEMS_FK3" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "GOPI"."WALMART_PRODUCTS" ("PRODUCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE BITMAP INDEX "GOPI"."WALMARTORDRITEMS" ON "GOPI"."WALMART_ORDERITEMS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "GOPI"."WALMART_ORDERS" 
   (	"ORDER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDER_DATE" DATE, 
	"ORDER_STATUS" VARCHAR2(20 CHAR), 
	"TOTAL_AMOUNT" NUMBER(10,2), 
	 CONSTRAINT "WALMART_ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CHECK_TOTAL_AMOUNT" CHECK (TOTAL_AMOUNT>=0) ENABLE, 
	 CONSTRAINT "CHECK_ORDER_STATUS" CHECK (order_status in 
('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')) ENABLE, 
	 CONSTRAINT "WALMART_ORDERS_FK1" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "GOPI"."WALMART_CUSTOMERS" ("CUSTOMER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "GOPI"."WALMARTCID" ON "GOPI"."WALMART_ORDERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "GOPI"."WALMARTORDATE" ON "GOPI"."WALMART_ORDERS" ("ORDER_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "GOPI"."WALMART_LOGS_TRG" 
AFTER INSERT OR DELETE OR UPDATE ON walmart_orders
FOR EACH ROW
DECLARE
    v_dml_type VARCHAR2(20);
    v_order_id walmart_orders.order_id%TYPE;
BEGIN
    IF INSERTING THEN
        v_dml_type := 'INSERT';
        v_order_id := :NEW.order_id;
    ELSIF DELETING THEN
        v_dml_type := 'DELETE';
        v_order_id := :OLD.order_id;
    ELSIF UPDATING THEN
        v_dml_type := 'UPDATE';
        v_order_id := :NEW.order_id;
    END IF;

    INSERT INTO walmart_logs (log_id, order_id, action, old_status, new_status, changed_by, changed_on)
    VALUES (walmart_logs_sequence.NEXTVAL, v_order_id, v_dml_type, :OLD.order_status, :NEW.order_status, USER, SYSDATE);
END;
/
ALTER TRIGGER "GOPI"."WALMART_LOGS_TRG" ENABLE;




  CREATE TABLE "GOPI"."WALMART_PAYMENTS" 
   (	"PAYMENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PAYMENT_METHOD" VARCHAR2(30 CHAR), 
	"AMOUNT" NUMBER(10,2), 
	"PAYMENT_STATUS" VARCHAR2(20 BYTE), 
	"TRANSACTION_DATE" DATE, 
	 CONSTRAINT "WALMART_PAYMENTS_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CHECK_PAYMENT_STATUS" CHECK (PAYMENT_STATUS IN ('SUCCESS','FAILED','REFUNDED')) ENABLE, 
	 CONSTRAINT "CHECK_PAYMENT_AMOUNT" CHECK (amount >=0) ENABLE, 
	 CONSTRAINT "WALMART_PAYMENTS_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "GOPI"."WALMART_ORDERS" ("ORDER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE INDEX "GOPI"."WALMARTPAYMENTS" ON "GOPI"."WALMART_PAYMENTS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;




  CREATE TABLE "GOPI"."WALMART_PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(30 CHAR), 
	"PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"STOCK_QUANTITY" NUMBER(5,0), 
	"REORDER_THRESHOLD" NUMBER(3,0), 
	 CONSTRAINT "WALMART_PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CHECK_STOCK_QUANTITY" CHECK (stock_quantity >=0) ENABLE, 
	 CONSTRAINT "CHECK_PRICE" CHECK (price >=0) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;




  CREATE TABLE "GOPI"."WALMART_SHIPPING" 
   (	"SHIPPING_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(50 CHAR), 
	"CARRIER" VARCHAR2(30 CHAR), 
	"TRACKING_NUMBER" VARCHAR2(30 CHAR), 
	"SHIPPED_DATE" DATE, 
	"DELIVERED_DATE" DATE, 
	 CONSTRAINT "WALMART_SHIPPING_PK" PRIMARY KEY ("SHIPPING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WALMART_SHIPPING_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "GOPI"."WALMART_ORDERS" ("ORDER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;



